Merge #72, #59, #45, Refactoryng and Theme System
DigitalLogicSimCommunity/Digital-Logic-Sim-CE pull request #79
Opened 2023-05-02 17:08 UTC by VitoBarra

Merged https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/pull/45. Made some alterations to to fix bugs, including making it work with zoom, making it work with small .bin files, and changing the IO to busses for ease of use.
Merged https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/pull/59.
Merged https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/pull/72. Fixed 2 minor bugs. Also changed the High-Z value from -1 (no longer usable due to uints) to a random number that hopefully won't be encountered in normal use. This could cause exceedingly difficult-to-trace bugs in people's circuits, but there's not really a different way to do it.
Increased zoom sensitivity since it was an issue with some users.
Credits haven't been updated so you may want to do that before merging.

In addition I have done 
- major refactoring of the project.
- Added a Theme system for customizable wire and signal colors.
- Enhanced the signal property menu to allow for group size and bus value changes

Know Issue: 
- Brocken Pin name display  (requires further refactoring)
- Preview signal misplacement with scale change

Future feature neaded:
- Ability to Save\load Selected theme Color (Theme System completion)
- Ability to Save\load Group size 
- Ability to Save\Signal WireType

I'm opening this despite the issue to let the community know about this work. Unfortunately, I've run out of time to dedicate to this project for now. So if anyone is interested in fix these issues starting with this PR I would be grateful.

Hopefully If I can find some time I will continue to work on this from time to time

2023-07-10 19:50 UTC, crispeeweevile commented
When will this PR be accepted? it's got a lot of cool features

2024-06-16 14:59 UTC, 901238746 commented
This is so cool, why hasn't it been approved yet?

2024-06-16 17:20 UTC, 901238746 commented
Man someone should approve this. Idk how to code but I dont think any of it is going to alt F4 the game

2024-06-16 17:27 UTC, 901238746 reviewed
Some of this looks fine but im a begginer. what happened to Palette.asset?

2024-06-16 17:49 UTC, 901238746 commented
I'd love this pull request because Im making a 11x16(11-bit 16 addresses) For my ALU and later I might need to make it 16 by 16 so that it would work with a better version of my ALUs LU(Logic Unit) so it can do more operations and comparisions.

2024-06-17 22:51 UTC, 901238746 approved these changes
This is fine

2024-06-23 10:44 UTC, AOx0 requested changes

2024-06-23 10:44 UTC, AOx0 commented on Assets/Modules/Save System/SaveSystem.cs
> +        string oldSaveDataPath = Path.Combine(oldAppDataPath, "SaveData");
I know you are actively working on the PR on your dev branch, just wanted to make you know about this one.

```cs
if (!Directory.Exists(oldAppDataPath)) return;
```

I believe the check does not actually make the cut; with a fresh build on a machine with a partial old path where the "Seb Lague" folder exists but not the "SaveData" (idk why) the code triggers an exception with the error:
```
DirectoryNotFoundException: Could not find a part of the path '/home/ae/.config/unity3d/Sebastian Lague/Digital Logic Sim/SaveData'.
```

However I think we can delay the check to validate `oldSaveDataPath` instead of `oldAppDataPath`. That way we verify the resource we are about to operate with actually exists and do not make assumptions based on the solely existence of "Seb Lague". 

This does work without triggering exceptions:

```diff
        string oldAppDataPath = Path.Combine(new string[]
        {
            Directory.GetParent(Application.persistentDataPath).Parent.FullName, "Sebastian Lague", "Digital Logic Sim"
        });
--      if (!Directory.Exists(oldAppDataPath)) return;

        string oldSaveDataPath = Path.Combine(oldAppDataPath, "SaveData");
++      if (!Directory.Exists(oldSaveDataPath)) return;
```

2024-06-23 14:31 UTC, VitoBarra commented on Assets/Modules/Save System/SaveSystem.cs
> +        string oldSaveDataPath = Path.Combine(oldAppDataPath, "SaveData");
Thank you for letting me know, I’ll take a look!

2024-06-28 16:08 UTC, VitoBarra commented
This should be good to go, some parts of the main menu are not very nice but they work

2024-07-08 17:07 UTC, AOx0 requested changes

2024-07-08 17:07 UTC, AOx0 commented on Assets/Scripts/UI/LoadProjectMenu.cs
> +        EditorUtility.RevealInFinder(SaveSystem.SaveDataDirectoryPath);
`UnityEditor.EditorUtility` is not available on release builds. I don't think we have any solution for this in the project yet, only the `StandaloneFileBrowser` plugin to open/save dirs and files.

We could hide the button and leave it for future PRs, though.

2024-07-08 17:18 UTC, AOx0 commented
Hey, I've been trying the PR, seems good in the Unity Editor, so far.
However, when producing a release build, the input system just stops working with pins, so wires don't work nor the activation/deactivation of the pins signal.

I suspect it's an issue with the new Unity Input system. I can reproduce the issue in the Unity Editor when changing the Event System components to the new suggested `Input System UI Input Module`.

My next thing on the list is to build the main branch's version and see if the issue is present there too, so I can discard the source code’s fault. Otherwise, if the main branch does work correctly, maybe it would be necessary to git bisect and revert whatever the change caused the button's fault. 

I don’t know if you are noticing the same on your end?

2024-07-08 22:35 UTC, VitoBarra commented on Assets/Scripts/UI/LoadProjectMenu.cs
> +        EditorUtility.RevealInFinder(SaveSystem.SaveDataDirectoryPath);
For now, I followed your advice and I have hidden the button

2024-07-08 23:14 UTC, VitoBarra commented
It happens on my machine (Windows) as well.
I will work on it, but after a first investigation, I founded out that issues arise when the SebInput Module is used. This module depends on the new input system, so probably needs to be updated or not used, as in the case of the signal handler that works fine.
I added a package (in the 3rdparty folder) that should be useful for debugging this problem.

2024-07-16 20:39 UTC, AOx0 commented
Thank you as always Vito! 

Just one little nitpick, I don't know if this is intentional, but the changing of pin colors does not display the correct color to be placed. i.e. It displays red but when placed the pin is green.

I'm willing to merge as-is and fix later tho, so I'll be just waiting for your confirmation whether to commit the merge or not.

2024-07-16 23:25 UTC, VitoBarra commented
I'm not sure that I understand the concern, but it is intentional that selecting the color for signals (input/output chip pins) and cables requires separate actions.

2024-07-21 00:35 UTC, AOx0 approved these changes

2024-07-21 00:35 UTC, AOx0 commented
Thank you Vito :D

2024-07-21 00:35 UTC, merged